"""Turn a stored thread into the two strings the answering step needs.

There are two, and conflating them is the mistake this module exists to avoid:

**The retrieval query.** Embeddings have no memory. "And what about the second
one?" is a perfectly clear question to a human reading the thread and a bag of
stopwords to bge-m3 -- it retrieves nothing, the distance gate rejects what
little it finds, and a thread that was working suddenly starts producing "a
member of our team will follow up". So a follow-up is rewritten into a
standalone question *before* it is embedded. This is the single change that
makes threading work at all.

**The history block.** The prior messages, put in front of the model at
generation time so the draft reads as part of a conversation rather than a
cold reply.

Both are bounded. A thread that runs long enough will not fit, and the failure
mode of ignoring that is not a clean error -- it is llama.cpp silently
truncating from the front, which drops the system prompt and takes the
grounding rules with it. Oldest messages are therefore dropped first and
replaced by a rolling summary, so the early part of a long thread degrades to a
paragraph instead of vanishing.

The summary is generated by the same local model and cached in the
conversations table, so a 30-message thread does not re-summarise its own
history on every new email.
"""

from __future__ import annotations

import os

import requests

from classifier.core import BASE_URL, SMALL_MODEL, auth_headers

from .store import Exchange, get_summary, history, set_summary

# Character budget for the rendered history block. Characters, not tokens: it
# is the number that can be checked without a tokeniser, and roughly 4x the
# token count for English prose. The 9B is served with a 32k context and the
# retrieved chunks already claim a slice of it, so this is deliberately modest.
MAX_HISTORY_CHARS = int(os.environ.get("THREAD_MAX_HISTORY_CHARS", "6000"))

# Turns newer than this many are never summarised away, however long they are.
# The most recent exchange is what a follow-up actually refers to.
KEEP_RECENT = int(os.environ.get("THREAD_KEEP_RECENT", "4"))

# A single enormous forwarded email should not evict the whole thread.
MAX_MESSAGE_CHARS = int(os.environ.get("THREAD_MAX_MESSAGE_CHARS", "2000"))

# Query rewriting costs one extra model call per email. Turn it off and
# follow-ups retrieve on their own words, which for "and the second one?" means
# retrieving nothing.
REWRITE_QUERY = os.environ.get("THREAD_REWRITE_QUERY", "1") not in ("0", "false", "")

REWRITE_SYSTEM = """Rewrite the user's latest email as a single standalone \
question that can be understood without the conversation.

Rules:
- Resolve pronouns and references ("it", "that level", "the second one") into \
the thing they refer to, using the conversation.
- Keep the enquirer's own wording wherever you can. Do not answer the question.
- Add no facts that are not in the conversation.
- If the latest email is already standalone, repeat it unchanged.
- Output the question and nothing else."""

SUMMARY_SYSTEM = """Summarise this portion of an email thread between an \
enquirer and a training institute.

Keep: what the enquirer asked about, what they were told, and any specifics \
(levels, modules, dates, names) that a later message might refer back to.
Drop: greetings, sign-offs, pleasantries.
Write at most six sentences of plain prose. Add nothing that is not stated."""


def _truncate(text: str, limit: int) -> str:
    text = text.strip()
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0] + " […]"


def render(exchanges: list[Exchange]) -> str:
    """The history block, oldest first: each turn's query, then its reply if any.

    A follow-up (threads.store.create_followup) is not a turn the enquirer
    took part in -- `query` holds a topic label the system chose, not
    something they wrote, and pairing it under "Enquirer:" would put words
    in their mouth they never said, then feed that fabrication back to the
    model as if it were real conversation history. It renders as our own
    message instead, with no "Enquirer:" line at all, and only once actually
    sent -- a follow-up still sitting in the review queue has not reached
    them yet, so it is not part of the conversation as far as they know.
    """
    lines = []
    for exchange in exchanges:
        if exchange.is_followup:
            if exchange.sent:
                lines.append(
                    f"Our follow-up (unprompted, not a reply to anything "
                    f"they asked):\n{_truncate(exchange.reply or '', MAX_MESSAGE_CHARS)}"
                )
            continue
        lines.append(f"Enquirer:\n{_truncate(exchange.query, MAX_MESSAGE_CHARS)}")
        if exchange.answered:
            lines.append(f"Our reply:\n{_truncate(exchange.reply, MAX_MESSAGE_CHARS)}")
    return "\n\n".join(lines)


def _call(system: str, user: str, *, max_tokens: int, timeout: int = 90) -> str:
    """One completion through the proxy. Returns "" on any failure.

    Failures are swallowed on purpose. Both callers are enhancements -- a
    rewritten query and a summary -- and a thread that cannot reach the model
    should degrade to the raw question and the raw history, not fail the email.
    """
    try:
        resp = requests.post(
            f"{BASE_URL}/chat/completions",
            json={
                "model": SMALL_MODEL,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                "temperature": 0,
                "max_tokens": max_tokens,
            },
            headers=auth_headers(),
            timeout=timeout,
        )
        resp.raise_for_status()
        return (resp.json()["choices"][0]["message"]["content"] or "").strip()
    except (requests.RequestException, KeyError, IndexError, ValueError):
        return ""


def standalone_question(email_text: str, prior: list[Exchange]) -> str:
    """Rewrite a follow-up into something that can be embedded on its own.

    Returns `email_text` unchanged when there is no prior context, when
    rewriting is disabled, or when the model call fails.
    """
    if not prior or not REWRITE_QUERY:
        return email_text

    rewritten = _call(
        REWRITE_SYSTEM,
        f"Conversation so far:\n\n{render(prior)}\n\n"
        f"Latest email:\n{email_text}\n\nStandalone question:",
        max_tokens=150,
    )

    # A rewrite that came back empty, or vastly longer than the original, is the
    # model having answered the question or padded it rather than condensed it.
    # Either way the original is safer to embed than an invented one.
    if not rewritten or len(rewritten) > len(email_text) + 400:
        return email_text
    return rewritten


def _summarise(exchanges: list[Exchange], previous: str) -> str:
    """Fold older turns (and any existing summary) into one paragraph."""
    prefix = f"Summary of the thread so far:\n{previous}\n\n" if previous else ""
    return _call(
        SUMMARY_SYSTEM,
        f"{prefix}Thread portion to summarise:\n\n{render(exchanges)}",
        max_tokens=300,
    )


def load(conversation_id: str) -> tuple[str, list[Exchange]]:
    """Assemble a thread into (history_block, recent_exchanges).

    Recent exchanges are returned separately because `standalone_question` wants
    real turns, not a rendered blob. The history block is what goes to the
    generation prompt: a rolling summary of the old part, then the recent turns
    in full.

    Summarising writes back to the store, so the cost is paid once per overflow
    rather than on every email in a long thread.
    """
    exchanges = history(conversation_id)
    if not exchanges:
        return ("", [])

    summary, through = get_summary(conversation_id)

    # Anything already covered by the stored summary is not rendered again.
    live = [e for e in exchanges if e.id > through]

    # Drop from the oldest end until the block fits, but never below KEEP_RECENT.
    dropped: list[Exchange] = []
    while len(live) > KEEP_RECENT and len(render(live)) > MAX_HISTORY_CHARS:
        dropped.append(live.pop(0))

    if dropped:
        fresh = _summarise(dropped, summary)
        if fresh:
            summary = fresh
            set_summary(conversation_id, summary, dropped[-1].id)
        else:
            # Summarisation failed. The turns are still dropped -- the budget is
            # a hard constraint -- but the store is not updated, so the next
            # email retries rather than permanently losing that stretch.
            pass

    block = render(live)
    if summary:
        block = f"Earlier in this thread:\n{summary}\n\n{block}".strip()

    return (block, live)
